#! python
# -*- coding: utf-8 -*-

# translations go in this directory

language_names = {   
    'ab' : " аҧсуа бызшәа",
    'af' : "Afrikaans",
    'am' : " አማርኛ",
    'ar' : "العربية",
    'az' : "Azərbaycan",
    'be' : "Беларуская",
    'bg' : "Български",
    'bm' : "Bamanankan",
    'ca' : "Català",
    'cs' : "čeština",
    'cy' : "Cymraeg",
    'da' : "Dansk",
    'de' : "Deutsch",
    'ee' : "Ɛʋɛ",
    'el' : "Ελληνικά",
    'en' : "English",
    'es' : "Español",
    'et' : "Eesti",
    'eu' : "Euskara",
    'fa' : "فارسی",
    'ff' : "Fulfulde, Pulaar, Pular",
    'fi' : "Suomi",
    'fr' : "Français",
    'fr-CA' : "Français canadien",
    'ga' : "Gaeilge",
    'gl' : "Galego",
    'ha' : "Hausa",
    'he' : "עברית",
    'hi' : "हिंदी",
    'hr' : "Hrvatski",
    'hu' : "Magyar",
    'hy' : "Հայերեն",
    'id' : "Bahasa indonesia",
    'is' : "Íslenska",
    'it' : "Italiano",
    'ja' : "日本語",
    'ka' : "ქართული ",
    'kk' : "Қазақ",
    'kn' : "ಕನ್ನಡ",
    'ko' : "한국어",
    'ky' : "Кыргыз",
    'lt' : "Lietuviškai",
    'luo' : "Dholuo",
    'lv' : "Latviešu",
    'mk' : "Македонски",
    'ms' : "Bahasa melayu",
    'mt' : "Malti",
    'nl' : "Nederlands",
    'no' : "Norsk",
    'pl' : "Polski",
    'ps' : " پښتو",
    'pt' : "Português",
    'pt-BR' : "Português brasileiro",
    'rn' : "Kirundi",
    'ro' : "Română",
    'ru' : "Pyccĸий",
    'rw' : "Kinyarwanda",
    'sk' : "Slovenčina",
    'sl' : "Slovenščina",
    'so' : "Somali",
    'sq' : "Shqip",
    'sr' : "Srpski Српски",
    'sv' : "Svenska",
    'sw' : "Kiswahili",
    'te' : "తెలుగు",
    'th' : "ภาษาไทย",
    'tr' : "Tϋrkçe",
    'uk' : "Українська",
    'ur' : "اردو",
    'uz' : "o'zbek",
    'vi' : "Tiếng Việt",
    'wo' : "Wolof",
    'xs' : "IsiXhosa",
    'yo' : "Yorùbá",
    'zh' : "中文",
    'zh-Hans' : "简体中文",
    'zh-Hant' : "繁體中文",
    'zu' : "IsiZulu",
}

def get_language_name(code):
    if code in language_names:
        return language_names[code]
    else:
        return code
    
